[runner]
seed = 42
total_episodes = 64
folder = "simulation_middle_late2"
agent = "SimulationAgent"
save = true 

[scheduler]
running_time = 400
gpu_changes = [{ time = 270, change = "up" }]
start_time = 270

[trainer]
weights = "results/small_middle_late2/weights.pth"
runtimes = "results/small_middle_late2/runtimes"

[job]
model = "ConvNet2"
dataset = "cifar10"

[agent]
device = 0
action_set_size = 4
num_actions = 3
save_file = "results/simulation_middle_late2/data.pkl"
