[runner]
seed = 42
total_episodes = 15000
folder = "test_simulation_learn"
agent = "Agent"

[simulation]
datafile = "results/test_simulation/data.pkl"

[job]
model = "ConvNet2"
dataset = "cifar10"

[agent]
decay_freq = 500
device = 0
vocab = "models"
alpha = 0.0001
hidden_size = 50
embedding_size = 16
max_actions = 4
decider_lstm_size = 16
decider_linear_size = 128
learning_rate_decay = 0.99
time_encoding_size = 8
